### ISSUE TITLE
Auto-save option for Org files

### ISSUE THREAD

**Issue by darkstego** [darkstego/wakib.d#1]
Current auto saving mechanism is not ideal when handling regularly updated and shared org files.

As org files are typically handled by cloud storage rather than version control, you get into a situation where forgetting to save causes a hassle of recovering the file from the auto-save. I do not think that setting `auto-save-visited-mode` is the answer as it would enable same file auto-save as the default behavior which it shouldn't be.

I have a solution of setting `org-save-all-org-buffer` on the auto-save hook, but that would prompt to save buffers with no associated files, which is not the behavior I would want.

I have also tried the package _really-auto-save_ and while it provides a better solution it caused the unintended behavior of causing intermittent freezes in some scenarios (e.g. it would trigger an auto-save of the magit buffer while typing in commit messages) So that was a no go.

**Comment by codygman** [comment]
You can enable `real-auto-save-mode` only for org buffers and selectively for others that it's appropriate for. I think that would be the ideal solution and the one I'll implement for others I'm recommending wakib to for using org-mode that don't already use emacs/vim.

**Comment by darkstego** [comment]
Thanks for the feedback. As I had mentioned, `real-auto-save` wasn't a great user experience due to intermittent freezes. I did eventually write my own based on `save-some-buffers` which I think I will add to the user template at this point. It gives the flexibility of only autosaving files under the location you would want (in my example those in shared in Dropbox). This would allow the user to set up the auto-save requirements as per their specification.
