### ISSUE TITLE
customization error during modification 

### ISSUE THREAD

**Issue by alarawms** [darkstego/wakib.d#11]
When trying to customize any variable through the customize menu, the field trun into %}: upon unfolding. 
![Screenshot_2021-09-02_23-20-35](https://user-images.githubusercontent.com/50319563/131911028-c2864abb-5ca9-4acc-87b1-482f0f6d2729.png)

**Comment by darkstego** [comment]
What OS/distro are you using? I will try to replicate it.

**Comment by alarawms** [comment]
Linux  5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Fedora 34

**Comment by alarawms** [comment]
Decrypting /home/xxxx/.authinfo.gpg...done
gnutls.el: (err=[-217] One of the involved algorithms has insufficient security level.) boot: (:priority NORMAL:%DUMBFW :hostname webmail.xxx.sa :loglevel 0 :min-prime-bits nil :trustfiles (/etc/pki/tls/certs/ca-bundle.crt /etc/ssl/cert.pem) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
smtpmail-send-command: Process smtpmail not running???? 
**it was running before like charm with vaniila emacs and doomemacs**

**Comment by darkstego** [comment]
What command triggers that error?

**Comment by alarawms** [comment]
Any customization. 
In this case face customization.

**Comment by alarawms** [comment]
I think the issue with starttls package.

**Comment by alarawms** [comment]
I think it is related to gnutls issue.

**Comment by darkstego** [comment]
So the good news is I was able to replicate the customization issue. I am working on a fix.

The TLS issue, I don't understand what it has to do with the customization interface. There shouldn't be any TLS connections happening at that point.

**Comment by alarawms** [comment]
Well proping the webmail server using gnutls-cli results in same error. 
Maybe tls version. 

I am digging into this too. 
Doom emacs implementation of gnutls maybe overcoming this.

**Comment by alarawms** [comment]
Well. I’ll work on it. Let me if the issue is related to OS or my configuration for mu4e smtp

**Comment by darkstego** [comment]
I think they discuss some of the TLS changes done in DoomEmacs [here](https://github.com/hlissner/doom-emacs/issues/1566)

**Comment by alarawms** [comment]
I had this lisp file for all my email and writing configuration since 3 years. It is time for refresh.

**Comment by darkstego** [comment]
The Customization Error has been resolved. It turns out that for some reason Customization menus calls the `substitute-command-keys` keys function without an argument, even though the definition a string argument is mandatory. Wakib-keys has an advice around that function that didn't deal with that. 

You can simply upgrade the `wakib-keys` package to get the fix.

I will be closing this issue since it is mainly about the customization issue. If you still have a problem with TLS then feel free to open up a new issue.

**Comment by alarawms** [comment]
Thanks for the great support. 
I am keen on using wakib.
