### ISSUE TITLE
Some question?

### ISSUE THREAD

**Issue by onekk** [darkstego/wakib.d#12]
Hello, I've installed wakib, using [chemacs2](https://github.com/plexus/chemacs2)

And it works.

I've a rather complex configuration involving lsp, latex and python so mainly:

lsp, lsp-latex, auctex, and some minor packages to make things works.

1) How to correctly install packages to have keybinding redefining works?

2) Some of my customization involve modifying some auctex behaviour through custom.el customization using the standard way, customize menu.

TIA and Reaards

Carlo D.

**Comment by darkstego** [comment]
1. You can setup any extra packages in the `user` directory in the `init-user.el` file. Ideally bindings should work if they simply remap functions like `next-line` and `right-char`, but not all packages do that and sometimes I have to map the bindings in that package's mode map. An example can be found in the init-user.el.template file in the repo, check the vterm section as an example
2.  The customize menu should work without a problem as far as I know. If you have any problems feel free to reach out to me.

**Comment by onekk** [comment]
Many Thanks.

I will try asap and let you know FYI for bad and for good.
