### ISSUE TITLE
Make undo tree default for undo or redo.el?

### ISSUE THREAD

**Issue by codygman** [darkstego/wakib.d#2]
The first big pain point I see even with introducing someone to wakib is the undo system. While it offers the advantage of being able to recover any state, it means that it "doesn't work right" and is alien to users.

Since undo is frequently the thing most people want to work right because it gives a sense of comfort in their editing experience, this is a big big concern.

Sure you could say users should be using source control, but many that this distro would target wouldn't have even heard of source control imo.

A few options in no particular order:

- Default to using undo-tree.el 

pros: lets users visualize changes and be lossless if undo-tree bugs don't mess everything up

 cons: very alien looking for someone just looking to C-z back to where they were like normal editors.

- Default to using redo.el

Pros: same user experience as other editors and what users expect from what I hear
Cons: lossless, but users wanting this are no worse off than with other editors and get advantages of emacs without too much alien stuff

Teach users regular emacs undo and convince them of lossless benefits
Pros: very reliable, stable, and always lossless way of preserving edit history
Cons: Most confusing option for users

**Comment by darkstego** [comment]
Thanks for this. undo-tree was on my radar as many starter kits seem to default to it. I will give them both a try and see.

**Comment by sinekonata** [comment]
undo-tree makes sense. I wouldn't want to lose the lossless undo from emacs though, that would seem counter to the way Wakib does things.

**Comment by darkstego** [comment]
Undo-Tree added. 

In case anyone revists this.
Redo.el and Redo+.el are old and unmaintained. Undo-fu is another viable options as of current date.

**Comment by sinekonata** [comment]
For those who like me don't know git well. To update (from `.emacs.d/`) :
```
git fetch --all
git pull origin master
```

It's an amazing package, exactly what I wanted :D
I don't know where to report this, so I'll do it here : the `M-j` and `M-l` keys don't work as the arrows in the tree view. Although all others are working, including `M-J` and `M-L` (for PgUp/PgDn).
In addition, I couldn't find out what `undo-tree-switch-branch` does because it systematically outputs `Wrong type argument: number-or-marker-p, nil`.

**Comment by darkstego** [comment]
You don't need all that. From `.emacs.d/` just do:
```
 git pull
```

Also, I fixed it so left, right work correctly now in undo-tree visualizer. If you notice any bugs or some feature request you can add it as a separate issue.
