### ISSUE TITLE
Minor error during install

### ISSUE THREAD

**Issue by noaccOS** [darkstego/wakib.d#5]
Error (use-package): Failed to install ivy-yasnippet: https://melpa.org/packages/ivy-yasnippet-20181002.1655.el: Bad Request

**Comment by darkstego** [comment]
I tried a new install and couldn't get the error. From the error message it seems like a melpa issue, which is likely a transient thing. 

You can try the following to fix the problem:
```
Alt-x package-refresh-contents
Alt-x package-reinstall
Then select: ivy-yasnippet
```
If you can't find the package then try `package-install` instead of `package-reinstall`
