### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by shaund** [darkstego/wakib.d#8]
When I try to customize some options, it looks like this:

![](https://user-images.githubusercontent.com/610782/77860682-4480a900-71c5-11ea-939c-97f818b07e53.png)

This is on a fresh install of the most recent code.

**Comment by darkstego** [comment]
I am not getting this problem. I even tried to replicate it with a fresh install on Linux and Windows.
This is on Emacs 26.3 and I go to Options -> Customize Emacs -> Top Level Customization Group.
This is what it looks like on my end.

![Screenshot_20200329_180342](https://user-images.githubusercontent.com/2610287/77862236-1791bd80-71e8-11ea-92f9-c8fd79a141e1.png)

The think I may have come across an issue like yours in the past, it kinda looks familiar. Unfortunately I don't remember the details. My guess is there is a problem with the custom.el file.

**Comment by sinekonata** [comment]
I do have the same issue. It's really odd that it's so hard to reproduce since I had the issue on a fresh install of the latest emacs + wakib.

**Comment by darkstego** [comment]
Are you using it on Windows, Linux or Mac?

Do you get any errors in the *messages* buffer?

**Comment by alarawms** [comment]
> When I try to customize some options, it looks like this:
> 
> ![](https://user-images.githubusercontent.com/610782/77860682-4480a900-71c5-11ea-939c-97f818b07e53.png)
> 
> This is on a fresh install of the most recent code.

same here , emacs 27.2

**Comment by darkstego** [comment]
Issue was from wakib-keys package, and has been fixed

**Comment by alarawms** [comment]
Thanks a lot.
